---
- name: Print all available facts for debugging
  # 'cd ansible; ansible localhost -m ansible.builtin.setup' will show this info
  ansible.builtin.debug:
    var: ansible_facts

- name: expand the root disk
  include_tasks: grow_disk.yml
  when: not in_container

- name: APT Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true
  when: is_debian

- name: RPM Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
  when: is_redhat

- name: APT Install Dev Tools and Gnome
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - vim
      - curl
      - sudo
      - "{{ distro.gnome_group }}"
  become: true
  when: is_debian

- name: RPM Install Development Tools
  dnf:
    name:
      - "@Development Tools"
      - vim
      - sudo
      - "@{{ distro.gnome_group }}"
    allowerasing: true # fix version conflicts for curl and coreutils on Rocky
  become: true
  when: is_redhat

- name: Change default target to graphical.target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
  become: true
  when: not in_container

- name: Make XOrg the default display manager
  ansible.builtin.lineinfile:
    path: "{{ distro.gdm_config }}"
    search_string: "WaylandEnable"
    line: "WaylandEnable=false"
  become: true
  when: not in_container

- name: create user
  ansible.builtin.user:
    name: "{{ dev_user }}"
    shell: /bin/bash
    createhome: true
    password: ""
    comment: "EPICS Developer"
  become: true

- name: Make users passwordless for sudo in group wheel
  lineinfile:
    path: /etc/sudoers
    regexp: "^%{{ dev_user }}"
    line: "%{{ dev_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  become: true

- name: ensure that python refers to python3 (fixes issue with Rocky container)
  ansible.builtin.file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  become: true
