epics_modules:
  base:
    name: "EPICS Base"
    version: "7.0.9"
    url: "https://github.com/epics-base/epics-base/releases/download/R7.0.9/base-7.0.9.tar.gz"
    release_var: "EPICS_BASE"
    release_sortkey: "99"
    add_to_path: true
    required_debs:
      - libreadline-dev
      - libncurses-dev
      - perl
      - libperl-dev
    required_rpms:
      - readline-devel
      - ncurses-devel
      - glibc-devel
      - perl
      - perl-devel
      - perl-Test-Simple
      - perl-Test-Harness
    pre_hook: base_prep.yml
    args: -j {{ ansible_facts.processor_vcpus }}

  pvxs:
    name: "PVXS"
    version: "1.3.1"
    url: "https://github.com/epics-base/pvxs/archive/refs/tags/1.3.1.tar.gz"
    release_var: "PVXS"
    release_sortkey: "10"
    add_to_path: true
    required_debs:
      - libevent-dev
      - libxml2-dev
    required_rpms:
      - libevent-devel
      - libxml2-devel
    args: -j {{ ansible_facts.processor_vcpus }}

  p4p:
    name: "p4p"
    version: "4.2.0"
    url: "https://github.com/epics-base/p4p/archive/refs/tags/4.2.0.tar.gz"
    release_var: "P4P"
    release_sortkey: "10"
    required_debs:
      - python3-dev
      - python3-numpy
      - python3-nose2
      - python-dev-is-python3
      - cython3
      - python3-setuptools
    required_rpms:
      - python3-devel
      - python3-numpy
      - python3-nose2
      - python3-Cython
    enable_repos:
      - crb
    args: -j {{ ansible_facts.processor_vcpus }}

  pvapy:
    name: "pvaPy"
    version: "5.3.1"
    url: "https://github.com/epics-base/pvaPy/archive/refs/tags/5.3.1.tar.gz"
    release_var: "PVAPY"
    release_sortkey: "10"
    required_debs:
      - autoconf
      - automake
      - python3-dev
      - libboost-python-dev
      - libboost-numpy-dev
      - python3-sphinx-rtd-theme
    required_rpms:
      - autoconf
      - automake
      - python3-devel
      - boost-python3-devel
      - boost-numpy3
      - python3-sphinx
      - python3-sphinx_rtd_theme
    enable_repos:
      - crb
    pre_hook: pvapy_prep.yml
    post_hook: pvapy_post.yml

  seq:
    name: "SNL Sequencer"
    version: "2.2.9"
    url: "https://github.com/epics-modules/sequencer/archive/refs/tags/R2-2-9.tar.gz"
    release_var: "SNCSEQ"
    release_sortkey: "10"
    add_to_path: true
    required_debs:
      - re2c
    required_rpms:
      - re2c
    args: -j {{ ansible_facts.processor_vcpus }}

  asyn:
    name: "ASYN"
    version: "4.44.2"
    url: "https://github.com/epics-modules/asyn/archive/refs/tags/R4-44-2.tar.gz"
    release_var: "ASYN"
    release_sortkey: "10"
    required_debs:
      - libtirpc-dev
    required_rpms:
      - rpcgen
      - libtirpc-devel
    enable_repos:
      - crb
    pre_hook: asyn_prep.yml
    args: -j {{ ansible_facts.processor_vcpus }}

  autosave:
    name: "autoSaveRestore"
    version: "5.11"
    url: "https://github.com/epics-modules/autosave/archive/refs/tags/R5-11.tar.gz"
    release_var: "AUTOSAVE"
    release_sortkey: "10"

  busy:
    name: "Busy Record"
    version: "1.7.4"
    url: "https://github.com/epics-modules/busy/archive/refs/tags/R1-7-4.tar.gz"
    release_var: "BUSY"
    release_sortkey: "10"

  sscan:
    name: "SScan module"
    version: "2.11.6"
    url: "https://github.com/epics-modules/sscan/archive/refs/tags/R2-11-6.tar.gz"
    release_var: "SSCAN"
    release_sortkey: "10"

  calc:
    name: "Calc module (misc records)"
    version: "3.7.5"
    url: "https://github.com/epics-modules/calc/archive/refs/tags/R3-7-5.tar.gz"
    release_var: "CALC"
    release_sortkey: "10"

  adcore:
    name: "AreaDetector - Core"
    version: "3.13"
    url: "https://github.com/areaDetector/ADCore/archive/refs/tags/R3-13.tar.gz"
    release_var: "ADCORE"
    release_sortkey: "10"
    required_debs:
      - zlib1g-dev
      - libxml2-dev
      - libtiff-dev
      - libtiff-tools
      - libjpeg-dev
      - libhdf5-dev
    required_rpms:
      - zlib-devel
      - libxml2-devel
      - libtiff-devel
      - libtiff-tools
      - libjpeg-devel
      - hdf5-devel
    enable_repos:
      - crb
    pre_hook: adcore_prep.yml

  adsimdetector:
    name: "AreaDetector - SimDetector"
    version: "2.11"
    url: "https://github.com/areaDetector/ADSimDetector/archive/refs/tags/R2-11.tar.gz"
    release_var: "ADSIMDETECTOR"
    release_sortkey: "10"
    pre_hook: adsimdetector_prep.yml

  adpvadriver:
    name: "AreaDetector - pvaDriver"
    version: "1.6"
    url: "https://github.com/areaDetector/pvaDriver/archive/refs/tags/R1-6.tar.gz"
    release_var: "PVADRIVER"
    release_sortkey: "10"
    pre_hook: adpvadriver_prep.yml

  opcua:
    name: "OPC UA Support (open62541)"
    version: "0.11.0"
    url: "https://github.com/epics-modules/opcua/archive/refs/tags/v0.11.0.tar.gz"
    release_var: "OPCUA"
    release_sortkey: "10"
    required_debs:
      - cmake
      - libssl-dev
      - libxml2-dev
    required_rpms:
      - cmake
      - openssl-devel
      - libxml2-devel
    pre_hook: opcua_prep.yml
    args: -j {{ ansible_facts.processor_vcpus }}
